### ISSUE TITLE
Support for PyTorch 2.0

### ISSUE THREAD

**Issue by anikethjr** [chrisby/torchMTL#6]
Hi,

Thank you for creating this useful package! I was wondering if the dependencies for this package could be updated on PyPI to support Pytorch 2.0. I tried installing the package along with Pytorch 2.0 (after manually changing the dependencies) and didn't face any obvious issues while using it.

Thank you,
Aniketh

**Comment by chrisby** [comment]
Hey Aniketh,

thanks for the interest in the package and reporting that it seems to work with PT2.0. I will take a look at updating the dependencies. 

Best,
Christian

**Comment by chrisby** [comment]
Updated the dependency.

**Comment by anikethjr** [comment]
Thank you so much, Christian!
